name: triage
on: push

jobs:
  triage:
    name: triage
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Run github-script
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (context.workflow != "Actions Linux") {
            console.log("Only posting reminder comment from 'Actions Linux' workflow. Skipping.")
            return
          }
